// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table TriviaTelemetry (eventId:string, eventType:string, type:string, eventName:string, userId:string, timestamp:datetime, properties:dynamic, context:dynamic, ingestedAtUtc:datetime) 
.create-or-alter table TriviaTelemetry ingestion json mapping 'TriviaTelemetryJson'
```
[{"Properties":{"Path":"$.eventId"},"column":"eventId","datatype":""},{"Properties":{"Path":"$.eventType"},"column":"eventType","datatype":""},{"Properties":{"Path":"$.type"},"column":"type","datatype":""},{"Properties":{"Path":"$.eventName"},"column":"eventName","datatype":""},{"Properties":{"Path":"$.userId"},"column":"userId","datatype":""},{"Properties":{"Path":"$.timestamp"},"column":"timestamp","datatype":""},{"Properties":{"Path":"$.properties"},"column":"properties","datatype":""},{"Properties":{"Path":"$.context"},"column":"context","datatype":""},{"Properties":{"Path":"$.ingestedAtUtc"},"column":"ingestedAtUtc","datatype":""}]
```
.create-or-alter table TriviaTelemetry ingestion json mapping 'TriviaTelemetry_mapping'
```
[{"Properties":{"Path":"$['eventId']"},"column":"eventId","datatype":""},{"Properties":{"Path":"$['eventType']"},"column":"eventType","datatype":""},{"Properties":{"Path":"$['type']"},"column":"type","datatype":""},{"Properties":{"Path":"$['eventName']"},"column":"eventName","datatype":""},{"Properties":{"Path":"$['userId']"},"column":"userId","datatype":""},{"Properties":{"Path":"$['timestamp']"},"column":"timestamp","datatype":""},{"Properties":{"Path":"$['properties']"},"column":"properties","datatype":""},{"Properties":{"Path":"$['context']"},"column":"context","datatype":""},{"Properties":{"Path":"$['ingestedAtUtc']"},"column":"ingestedAtUtc","datatype":""}]
```
.create-merge table raw_events (eventId:string, eventType:string, type:string, eventName:string, userId:string, timestamp:datetime, properties:dynamic, context:dynamic, ingestedAtUtc:datetime) 
.create-or-alter table raw_events ingestion json mapping 'raw_events_mapping'
```
[{"Properties":{"Path":"$['eventId']"},"column":"eventId","datatype":""},{"Properties":{"Path":"$['eventType']"},"column":"eventType","datatype":""},{"Properties":{"Path":"$['type']"},"column":"type","datatype":""},{"Properties":{"Path":"$['eventName']"},"column":"eventName","datatype":""},{"Properties":{"Path":"$['userId']"},"column":"userId","datatype":""},{"Properties":{"Path":"$['timestamp']"},"column":"timestamp","datatype":""},{"Properties":{"Path":"$['properties']"},"column":"properties","datatype":""},{"Properties":{"Path":"$['context']"},"column":"context","datatype":""},{"Properties":{"Path":"$['ingestedAtUtc']"},"column":"ingestedAtUtc","datatype":""}]
```
.create-merge table Images (Name:string, EncryptedImage:string, URL:string) 
.create-or-alter table Images ingestion csv mapping 'Images_mapping'
```
[{"Properties":{"Ordinal":"0"},"column":"Name","datatype":""},{"Properties":{"Ordinal":"1"},"column":"EncryptedImage","datatype":""},{"Properties":{"Ordinal":"2"},"column":"URL","datatype":""}]
```
.create-merge table locations (AdminDivision1:string, CountryRegion_ShortName:string, CountryRegion_LongName:string, Longitude:real, Latitude:real) 
.create-or-alter table locations ingestion csv mapping 'locations_mapping'
```
[{"Properties":{"Ordinal":"0"},"column":"AdminDivision1","datatype":""},{"Properties":{"Ordinal":"1"},"column":"CountryRegion_ShortName","datatype":""},{"Properties":{"Ordinal":"2"},"column":"CountryRegion_LongName","datatype":""},{"Properties":{"Ordinal":"3"},"column":"Longitude","datatype":""},{"Properties":{"Ordinal":"4"},"column":"Latitude","datatype":""}]
```
.create-or-alter function with (skipvalidation = "true") TriviaEvents() { TriviaTelemetry | summarize arg_max(ingestedAtUtc, *) by eventId }
.create-or-alter function with (skipvalidation = "true") allSessions(eventDate:datetime) {
let localEventDate = datetime_utc_to_local(eventDate, 'Europe/Madrid');
let startGame = 
    raw_events
    | extend localtime=datetime_utc_to_local(timestamp, 'Europe/Madrid')
    | where localtime between (startofday(localEventDate) .. endofday(localEventDate))
    | where ["type"] == "game"
    | where eventName in  ("game.start")
    | project
        eventType,
        type,
        start=eventName,
        userId,
        startTime=localtime,
        sessionId = toguid(properties.sessionId),
        questionCount = toint(properties.questionCount),
        pool=tostring(context.poolName),
        timestamp;
let score=
    raw_events
    | extend localtime=datetime_utc_to_local(timestamp, 'Europe/Madrid')
    | where localtime between (startofday(localEventDate) .. endofday(localEventDate))
    | where eventName == "game.answerquestion"
    | where isnotempty(FinalScore= tostring(properties.totalScore))
    | summarize arg_max (localtime, *) by sessionId = toguid(properties.sessionId)
    | project sessionId, FinalScore= toint(properties.totalScore);
let name=
    raw_events
    | extend localtime=datetime_utc_to_local(timestamp, 'Europe/Madrid')
    | where localtime between (startofday(localEventDate) .. endofday(localEventDate))
    | where eventName == "user.register"
    | distinct
        userId,
        userName = tostring(properties.name),
        country=tostring(properties.country),
        state=tostring(properties.state);
let endGame =
    raw_events
    | extend localtime=datetime_utc_to_local(timestamp, 'Europe/Madrid')
    | where localtime between (startofday(localEventDate) .. endofday(localEventDate))
    | where ["type"] == "game"
    | where eventName in  ("game.ended")
    | project
        eventType,
        type,
        end=eventName,
        endTime=localtime,
        sessionId = toguid(properties.sessionId),
        questionsAnswered = toint(properties.questionsAnswered),
        correctAnswers=toint(properties.correctAnswers),
        streaksCompleted=toint(properties.streaksCompleted),
        timeRemaining=toint(properties.timeRemaining),
        stationId=tostring(context.stationId);
startGame
| join kind=leftouter name on userId
| lookup endGame on sessionId
| lookup score on sessionId
| extend gameTime = case(isempty(endTime), (now() - startTime), endTime - startTime)}
.create-or-alter function with (skipvalidation = "true") questionsBySession(eventDate:datetime) {let sessionlist=
    currentSession(eventDate)
    | summarize make_list(sessionId);
    raw_events
    | where ["type"] == "game" 
    | where eventName == "game.answerquestion"
    | where properties.sessionId in (sessionlist)
    | summarize arg_max(timestamp, *) by tostring(properties.sessionId)
    | extend questionId = tostring(properties.questionId), isCorrect = tobool(properties.isCorrect)
    | lookup external_table('Questions') on $left.questionId == $right.id
    | project questionText}
.create-or-alter function with (folder = "Calendar", skipvalidation = "true") Calendar(DaysBack:timespan=time(30.00:00:00), Precision:timespan=time(1.00:00:00)) {
    let _startDate = startofday(ago(DaysBack));
     let _endDate = startofday(now());
     range Date from _startDate to _endDate step Precision
    | extend
        ["Year"]=getyear(["Date"]),
        ["Month"]=getmonth(["Date"]),
        ["Week of Year"]=week_of_year(["Date"]),
        ["Week of Month"]=(dayofmonth(["Date"]) / 7) + 1,
        ["Day"]=datepart('day', ["Date"])
}
.create-or-alter function with (skipvalidation = "true") leaderboard(EventDate:datetime, top:int=10) {
    let NumStreaks = raw_events
        | extend localtime=datetime_utc_to_local(timestamp,'Europe/Madrid')
        | where localtime between (startofday(EventDate) .. endofday(EventDate))
        | extend sessionId = toguid(properties.sessionId)
        | summarize streakCount=countif(eventName == "game.streakcompleted"), timestamp=min(timestamp), localtime=min(localtime) by userId,sessionId;
     allSessions(EventDate)
    | lookup NumStreaks on userId, sessionId
    | where not(userName == "Tidy Measure Maker 2" and startofday(datetime_utc_to_local(EventDate, 'Europe/Madrid')) in (datetime(2026-09-30), startofday(datetime_utc_to_local(now(), 'Europe/Madrid'))))
    | project userName, FinalScore, correctAnswers, streakCount, stationId,timestamp,localtime,userId,pool
    | lookup stationImages on stationId
    | lookup Images on $left.pool == $right.Name
    | extend URL=iff(pool=="SQL","https://i.postimg.cc/cHb6Gz8h/SQL.png","https://i.postimg.cc/FHMZNP0h/Fabric_final_x256_1.png")
    | summarize arg_max(FinalScore,*) by userName
        // | where userName !in ("Jeff Struthers","Tyler","Matt Hicks","Hanselman")
    | top ['top'] by FinalScore desc 
    | serialize
    | sort by FinalScore desc, localtime asc
    | extend Rank= row_number()
    | extend userName = iff(strlen(userName)<=20,userName,strcat(substring(userName,0,20),"..."))
}
.create-or-alter function with (skipvalidation = "true") stationImages() {
datatable(stationId:string,imageUrl:string,wizzardName:string)[
   "quantumqueryist","https://i.postimg.cc/X79tB84Y/QQ-v4-2.png?v=20260928","Quantum Queryist",
   "insightsalchemist","https://i.postimg.cc/G2pXMFWJ/IA-v2-1.png","Insights Alchemist",
   "dashboarddruid","https://i.postimg.cc/Cx56Q080/DD-v2-(1).png","Dashboard Druid"
]
}
.create-or-alter function with (skipvalidation = "true") topEasiestCategory(EventDate:datetime, top:int) {
answersCategory
| sort by percentageCorrect desc 
| extend EasyQuestion=percentageCorrect
| take top
}
.create-or-alter function with (skipvalidation = "true") topHardestCategory(EventDate:datetime, top:int) {
answersCategory
| sort by percentageIncorrect desc 
| extend EasyQuestion=percentageIncorrect
| take top
}
.create-or-alter function with (skipvalidation = "true") stationStatistics(EventDate:datetime) {
    raw_events
| where eventName == "game.answerquestion"
| extend stationId = tostring(context.stationId), isCorrect=tobool(properties.isCorrect), category=tostring(context.category)
| summarize CorrectQuestions=countif(isCorrect), IncorrectQuestions=countif(not(isCorrect)) by stationId, category
| lookup stationImages on stationId
}
.create-or-alter function with (skipvalidation = "true") answersCategory() {
        raw_events
| where eventName == "game.answerquestion"
| extend isCorrect=tobool(properties.isCorrect)
//| where tobool(properties.isCorrect) == false
| summarize CorrectAnswers=countif(isCorrect),IncorrectAnswers=countif(not(isCorrect)), TotalAnswers=count() by tostring(properties.category)
| extend percentageCorrect = toreal(CorrectAnswers)/toreal(TotalAnswers), percentageIncorrect=toreal(IncorrectAnswers)/toreal(TotalAnswers)
}
.create-or-alter function with (skipvalidation = "true") currentSession(eventDate:datetime) {
    allSessions(eventDate)
    | where isempty(end) //and gameTime < timespan(4 m)
}
.create-or-alter function with (skipvalidation = "true") FabricPool() {
    allSessions(now())
    | where pool contains "Fabric"
    | extend JoinKey = iff(isnotempty(state), state, country)
    | join kind=leftouter (
        locations
        | extend JoinKey = iff(CountryRegion_ShortName == "United States", AdminDivision1, CountryRegion_ShortName)
        | project JoinKey, CountryRegion_ShortName, AdminDivision1, Longitude, Latitude
    ) on JoinKey
    | project state, country, pool, Longitude, Latitude, correctAnswers
    | summarize totalCorrectAnswers=sum(correctAnswers) by tostring(pool), country, state, Longitude, Latitude
    | where totalCorrectAnswers > 0 and isnotnull(Longitude) and isnotnull(Latitude)
    | extend circle_geometry = geo_point_buffer(Longitude, Latitude, 75000)
}
.create-or-alter function with (skipvalidation = "true") SQLPool() {
    allSessions(now())
    | where pool contains "SQL"
    | extend JoinKey = iff(isnotempty(state), state, country)
    | join kind=leftouter (
        locations
        | extend JoinKey = iff(CountryRegion_ShortName == "United States", AdminDivision1, CountryRegion_ShortName)
        | project JoinKey, CountryRegion_ShortName, AdminDivision1, Longitude, Latitude
    ) on JoinKey
    | project state, country, pool, Longitude, Latitude, correctAnswers
    | summarize totalCorrectAnswers=sum(correctAnswers) by tostring(pool), country, state, Longitude, Latitude
    | where totalCorrectAnswers > 0 and isnotnull(Longitude) and isnotnull(Latitude)
    | extend circle_geometry = geo_point_buffer(Longitude, Latitude, 75000)
}
.create-or-alter function with (skipvalidation = "true") allSessionsToday(dummy:int=0) { allSessions(now()) }
.create-or-alter function with (skipvalidation = "true") leaderboardToday(dummy:int=0) { leaderboard(now(), 10) }
.create-or-alter function with (skipvalidation = "true") leaderboardPreviousDay(dummy:int=0) { leaderboard(ago(1d), 3) }
.create-or-alter function with (skipvalidation = "true") topEasiestCategoryToday(dummy:int=0) { topEasiestCategory(now(), 3) }
.create-or-alter function with (skipvalidation = "true") topHardestCategoryToday(dummy:int=0) { topHardestCategory(now(), 3) }
.create-or-alter function with (skipvalidation = "true") stationStatisticsToday(dummy:int=0) { stationStatistics(now()) }
.create-or-alter materialized-view  station_map on table raw_events { raw_events
    | where eventName == "user.register"
    | extend station=tostring(context.stationId)
    | where isnotempty(station)
    | summarize arg_max(timestamp, station) by userId }
.create-or-alter materialized-view  pool_map on table raw_events { raw_events
    | where eventName == "game.start"
    | extend pool=tostring(context.poolName), session=tostring(properties.sessionId)
    | summarize arg_max(timestamp, pool) by session }
